baseURL: 'https://sunny7712.github.io/'
languageCode: 'en-us'
title: "Vamsi's Blog"
theme: PaperMod
math: true
copyright: "© Vamsi"
pagination:
  pagerSize: 5

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true


outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production  # Enables SEO-related features like OpenGraph, Twitter Cards, Schema
  disableSpecial1stPost: true
  description: "A personal blog by Vamsi."
  author: "Vamsi"
  defaultTheme: auto
  ShowShareButtons: true
  ShowReadingTime: true
  ShowToc: true
  ShowCodeCopyButtons: true
  ShowPageNums: true
  math: true

  socialIcons:
    - name: "github"
      url: "https://github.com/sunny7712"
    - name: "x"
      url: "https://x.com/VamsiK76294"

  editPost:
    URL: "https://github.com/sunny7712/blog/tree/main/content"
    Text: "Suggest Changes"
    appendFilePath: true
  
  assets:
    favicon: "favicon.ico"
    favicon16x16: "favicon-16x16.png"
    favicon32x32: "favicon-32x32.png"
    apple_touch_icon: "apple-touch-icon.png"
    safari_pinned_tab: "safari-pinned-tab.svg"
    theme_color: "#2e2e33" # Change to match your site's theme
    msapplication_TileColor: "#2e2e33" # Change if needed

markup:
  goldmark:
    renderer:
      unsafe: true  # Allows raw HTML inside markdown
  highlight:
    noClasses: false

services:
  instagram:
    disableInlineCSS: true
  x:
    disableInlineCSS: true